### ISSUE TITLE
Parse non-biblical literature and other religion's scriptures

### ISSUE THREAD

**Issue by shivermetim** [DanteCoder/JoplinBibleQuote#32]
Hey mate, thank you for the plug-in. It's been really useful and I love it. I'm not a coder, I need to say that out the outset so please ignore me if I'm off base, but I'm wondering how feasible it would be to tweak the parser to process other scriptures, or even for example the writings of the Apostolic Fathers or pseudepigraphical texts?

For example I created an OSIS file of the Book of Mormon and the Doctrine and Covenants of the LDS church. Of course, the plug-in can't parse it.

There are set abbreviations for the books of the Book of Mormon as there are for the Apostolic Fathers (for example Ignatius' epistle to the Romans is 'Ign.Rom.'. Is there any way the parser could be tweaked to recognise these abbreviations?

**Comment by DanteCoder** [comment]
Hi! The plugin's scope is to cover the traditional Bible.
Either way, the parser used in the plugin is from another library: [Bible Passage Reference Parser](https://github.com/openbibleinfo/Bible-Passage-Reference-Parser), the list of books they support can be seen [here](https://github.com/openbibleinfo/Bible-Passage-Reference-Parser/blob/537560a73f53b61d39264819ba94160bda969b8a/src/en/book_names.txt).
