### ISSUE TITLE
Rendering not working

### ISSUE THREAD

**Issue by Gitomu** [DanteCoder/JoplinBibleQuote#35]
I recently installed the plugin and noticed the rendering part is not working as expected. I made sure the settings are properly configured:

![image](https://github.com/DanteCoder/JoplinBibleQuote/assets/108634490/0772c637-d27c-48f1-bdd8-aeaaf3bd7000)

But I still get no proper rendering:

![image](https://github.com/DanteCoder/JoplinBibleQuote/assets/108634490/d31bf095-c4e1-4e78-84cf-40ddea6b9c6a)

**Comment by DanteCoder** [comment]
Have you tried adding the bible extension ".xml"?
